apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<username>/intro-argo-cd-tutorial' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-stg.yaml
  destination:
    namespace: guestbook-stg
    name: dev # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
