apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/<username>/intro-argo-cd-tutorial'
    path: guestbook
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    namespace: guestbook-dev
    name: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
