name: Build
on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            dockerfile:
              - 'Dockerfile'

      - if: steps.changes.outputs.dockerfile == 'true'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - if: steps.changes.outputs.dockerfile == 'true'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - if: steps.changes.outputs.dockerfile == 'true'
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # GHCR requires lowercase.
      - if: steps.changes.outputs.dockerfile == 'true'
        id: repo-lower
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - if: steps.changes.outputs.dockerfile == 'true'
        uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 7
      
      - if: steps.changes.outputs.dockerfile == 'true'
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ steps.repo-lower.outputs.lowercase }}:${{ steps.short-sha.outputs.sha }}, ghcr.io/${{ steps.repo-lower.outputs.lowercase }}:latest